### ISSUE TITLE
no possibility for a blackhole

### ISSUE THREAD

**Issue by DiamondMiner1** [DaIsimsiz/AR-planetDef-Builder#6]
**Describe the bug**
Creation of a blackhole via. attributes is not possible

**To Reproduce**
1. go into the star options
2. enter "new attributes"
3. command gets ignored

**Expected behavior**
being able to add aspects, or getting a question on what attribute i want to add

**Screenshots**
- none available -
The program simply deletes the command

**Comment by DaIsimsiz** [comment]
The issue was caused by checking what attributes a star is missing by referencing the star's attributes to see what is missing from the complete list of attributes, which is the wrong way.

It will now check what is missing from the list of attributes, referencing from the complete list.

The fix will be pushed in the next release, which will arrive in about 15 minutes~.
